In [ ]:
import pandas as pd
#importing all relevant files :)
path="../../01_experiment/recordings/21_06_26_lab/"
part_df=pd.read_csv(path+"m.csv")
gazeSamples_df=pd.read_table(path+"m.tsv")
gazeSamples_df_reduced=gazeSamples_df[["TIME","BPOGX","BPOGY","BPOGV","USER"]]

543

In [26]:
part_df

,acc,accuracy,audio_file,average_response_time,avg_rt,background,block_size,canvas_backend,clock_backend,color_backend,...,time_sentence_audio,time_trial_loop,time_trial_sequence,time_welcome,timeout,title,total_correct,total_response_time,total_responses,width
0,undefined,undefined,48_n.wav,undefined,undefined,black,256,psycho,psycho,psycho,...,159199.6838,154867.8869,155114.7329,5065.9205,3000,SceneViewing,0,0.000000,0,1920
1,100,100,37_n.wav,6441,6441,black,256,psycho,psycho,psycho,...,173538.5890,154867.8869,169481.8167,5065.9205,3000,SceneViewing,1,6441.363900,1,1920
2,100,100,24_r.wav,5603,5603,black,256,psycho,psycho,psycho,...,185499.7357,154867.8869,181443.0413,5065.9205,3000,SceneViewing,2,11207.906900,2,1920
3,100,100,16_r.wav,4541,4541,black,256,psycho,psycho,psycho,...,195203.9516,154867.8869,191147.9872,5065.9205,3000,SceneViewing,3,13623.499000,3,1920
4,100,100,27_n.wav,4287,4287,black,256,psycho,psycho,psycho,...,206021.4696,154867.8869,201961.7645,5065.9205,3000,SceneViewing,4,17148.289600,4,1920
5,100,100,2_r.wav,4258,4258,black,256,psycho,psycho,psycho,...,217173.2466,154867.8869,213114.3792,5065.9205,3000,SceneViewing,5,21293.495000,5,1920
6,100,100,41_n.wav,4063,4063,black,256,psycho,psycho,psycho,...,227855.3628,154867.8869,223796.2418,5065.9205,3000,SceneViewing,6,24379.948600,6,1920
7,100,100,43_n.wav,4014,4014,black,256,psycho,psycho,psycho,...,238757.5668,154867.8869,234699.4550,5065.9205,3000,SceneViewing,7,28099.010900,7,1920
8,100,100,20_r.wav,3889,3889,black,256,psycho,psycho,psycho,...,248803.3988,154867.8869,244745.4365,5065.9205,3000,SceneViewing,8,31115.280400,8,1920
9,100,100,4_r.wav,3907,3907,black,256,psycho,psycho,psycho,...,260211.6875,154867.8869,256153.5604,5065.9205,3000,SceneViewing,9,35164.158500,9,1920
10,100,100,18_r.wav,3793,3793,black,256,psycho,psycho,psycho,...,270135.1737,154867.8869,266078.1013,5065.9205,3000,SceneViewing,10,37933.960300,10,1920
11,100,100,0_r.wav,3691,3691,black,256,psycho,psycho,psycho,...,280048.8473,154867.8869,275990.0320,5065.9205,3000,SceneViewing,11,40607.390000,11,1920
12,100,100,3_r.wav,3571,3571,black,256,psycho,psycho,psycho,...,289253.5524,154867.8869,285196.2894,5065.9205,3000,SceneViewing,12,42858.780100,12,1920
13,100,100,42_n.wav,3461,3461,black,256,psycho,psycho,psycho,...,298759.6302,154867.8869,294703.6368,5065.9205,3000,SceneViewing,13,45004.274700,13,1920
14,100,100,30_n.wav,3434,3434,black,256,psycho,psycho,psycho,...,309007.7935,154867.8869,304947.6134,5065.9205,3000,SceneViewing,14,48085.415800,14,1920
15,100,100,5_r.wav,3342,3342,black,256,psycho,psycho,psycho,...,318332.0504,154867.8869,314275.1909,5065.9205,3000,SceneViewing,15,50139.016500,15,1920
16,100,100,21_r.wav,3262,3262,black,256,psycho,psycho,psycho,...,327763.8384,154867.8869,323706.3717,5065.9205,3000,SceneViewing,16,52194.405500,16,1920
17,100,100,32_n.wav,3216,3216,black,256,psycho,psycho,psycho,...,337801.6499,154867.8869,333740.1302,5065.9205,3000,SceneViewing,17,54687.191500,17,1920
18,100,100,33_n.wav,3125,3125,black,256,psycho,psycho,psycho,...,346596.3673,154867.8869,342539.0483,5065.9205,3000,SceneViewing,18,56260.677800,18,1920
19,100,100,25_n.wav,3046,3046,black,256,psycho,psycho,psycho,...,355654.8830,154867.8869,351595.9535,5065.9205,3000,SceneViewing,19,57887.847400,19,1920
20,100,100,38_n.wav,3006,3006,black,256,psycho,psycho,psycho,...,365208.9023,154867.8869,361148.2930,5065.9205,3000,SceneViewing,20,60126.204600,20,1920
21,100,100,35_n.wav,2968,2968,black,256,psycho,psycho,psycho,...,374748.1538,154867.8869,370690.0628,5065.9205,3000,SceneViewing,21,62329.189600,21,1920
22,100,100,6_r.wav,2946,2946,black,256,psycho,psycho,psycho,...,384841.6601,154867.8869,380785.7566,5065.9205,3000,SceneViewing,22,64814.131100,22,1920
23,100,100,36_n.wav,2880,2880,black,256,psycho,psycho,psycho,...,394029.8869,154867.8869,389972.2877,5065.9205,3000,SceneViewing,23,66250.218000,23,1920
24,100,100,12_r.wav,2867,2867,black,256,psycho,psycho,psycho,...,403889.9563,154867.8869,399832.2402,5065.9205,3000,SceneViewing,24,68812.111500,24,1920
25,100,100,10_r.wav,2831,2831,black,256,psycho,psycho,psycho,...,412907.1978,154867.8869,408848.7645,5065.9205,3000,SceneViewing,25,70788.762801,25,1920
26,100,100,40_n.wav,2795,2795,black,256,psycho,psycho,psycho,...,422739.6153,154867.8869,418680.0117,5065.9205,3000,SceneViewing,26,72671.464700,26,1920
27,100,100,49_n.wav,2773,2773,black,256,psycho,psycho,psycho,...,432143.0957,154867.8869,428086.7779,5065.9205,3000,SceneViewing,27,74875.199400,27,1920
28,100,100,44_n.wav,2742,2742,black,256,psycho,psycho,psycho,...,441259.7713,154867.8869,437203.3669,5065.9205,3000,SceneViewing,28,76788.530200,28,1920
29,100,100,17_r.wav,2743,2743,black,256,psycho,psycho,psycho,...,451490.4933,154867.8869,447429.9011,5065.9205,3000,SceneViewing,29,79558.744101,29,1920
30,100,100,31_n.wav,2708,2708,black,256,psycho,psycho,psycho,...,460196.0421,154867.8869,456135.7142,5065.9205,3000,SceneViewing,30,81246.815901,30,1920
31,100,100,23_r.wav,2686,2686,black,256,psycho,psycho,psycho,...,469686.6183,154867.8869,465630.0576,5065.9205,3000,SceneViewing,31,83269.506200,31,1920
32,100,100,29_n.wav,2673,2673,black,256,psycho,psycho,psycho,...,479075.7236,154867.8869,475015.8311,5065.9205,3000,SceneViewing,32,85557.824700,32,1920
33,100,100,28_n.wav,2671,2671,black,256,psycho,psycho,psycho,...,490141.7429,154867.8869,486085.7847,5065.9205,3000,SceneViewing,33,88173.128800,33,1920
34,100,100,1_r.wav,2634,2634,black,256,psycho,psycho,psycho,...,498606.9639,154867.8869,494547.0983,5065.9205,3000,SceneViewing,34,89573.600900,34,1920
35,100,100,13_r.wav,2609,2609,black,256,psycho,psycho,psycho,...,507524.7709,154867.8869,503466.0541,5065.9205,3000,SceneViewing,35,91330.341000,35,1920
36,100,100,11_r.wav,2582,2582,black,256,psycho,psycho,psycho,...,516610.9746,154867.8869,512550.7237,5065.9205,3000,SceneViewing,36,92955.820200,36,1920
37,100,100,34_n.wav,2574,2574,black,256,psycho,psycho,psycho,...,525453.4042,154867.8869,521397.1252,5065.9205,3000,SceneViewing,37,95252.268400,37,1920
38,100,100,46_n.wav,2556,2556,black,256,psycho,psycho,psycho,...,534598.2237,154867.8869,530540.1718,5065.9205,3000,SceneViewing,38,97161.718800,38,1920
39,100,100,47_n.wav,2538,2538,black,256,psycho,psycho,psycho,...,544225.9231,154867.8869,540168.5963,5065.9205,3000,SceneViewing,39,98990.816401,39,1920
40,100,100,7_r.wav,2521,2521,black,256,psycho,psycho,psycho,...,553349.3561,154867.8869,549292.0387,5065.9205,3000,SceneViewing,40,100871.478100,40,1920
41,100,100,15_r.wav,2522,2522,black,256,psycho,psycho,psycho,...,563410.1789,154867.8869,559351.1630,5065.9205,3000,SceneViewing,41,103409.447600,41,1920
42,100,100,19_r.wav,2510,2510,black,256,psycho,psycho,psycho,...,572870.5935,154867.8869,568812.0767,5065.9205,3000,SceneViewing,42,105423.215600,42,1920
43,100,100,14_r.wav,2498,2498,black,256,psycho,psycho,psycho,...,581997.7676,154867.8869,577940.7316,5065.9205,3000,SceneViewing,43,107430.476500,43,1920
44,100,100,9_r.wav,2493,2493,black,256,psycho,psycho,psycho,...,591377.0689,154867.8869,587318.7916,5065.9205,3000,SceneViewing,44,109704.855800,44,1920
45,100,100,45_n.wav,2511,2511,black,256,psycho,psycho,psycho,...,601711.9204,154867.8869,597656.0707,5065.9205,3000,SceneViewing,45,113034.555300,45,1920
46,100,100,39_n.wav,2493,2493,black,256,psycho,psycho,psycho,...,610604.5887,154867.8869,606547.3972,5065.9205,3000,SceneViewing,46,114680.028500,46,1920
47,100,100,26_n.wav,2471,2471,black,256,psycho,psycho,psycho,...,619212.5266,154867.8869,615151.6687,5065.9205,3000,SceneViewing,47,116152.930500,47,1920
48,100,100,8_r.wav,2457,2457,black,256,psycho,psycho,psycho,...,628661.6037,154867.8869,624603.5967,5065.9205,3000,SceneViewing,48,117946.390200,48,1920
49,100,100,22_r.wav,2436,2436,black,256,psycho,psycho,psycho,...,637516.7517,154867.8869,633460.3619,5065.9205,3000,SceneViewing,49,119407.780500,49,1920

In [13]:
path_groupedCSV="../../01_experiment/stimuli/creatingDataStructure/"
g1_df=pd.read_csv(path_groupedCSV+"participant_group1.csv")
g2_df=pd.read_csv(path_groupedCSV+"participant_group2.csv")
g3_df=pd.read_csv(path_groupedCSV+"participant_group3.csv")
g4_df=pd.read_csv(path_groupedCSV+"participant_group4.csv")
g1_df

,id,image_nosub,image_sub,position1,position2,position3,position4,audio_file,sentence,condition,target_position,timeout
0,0,1_pos1_nosub.png,1_pos1_sub.png,cake,toy-car,toy-train,ball,0_r.wav,The boy will eat the cake,restrictive,1,3000
1,1,2_pos2_nosub.png,2_pos2_sub.png,lipstick,wine,cheese,chair,1_r.wav,The woman will drink the wine,restrictive,2,3000
2,2,3_pos3_nosub.png,3_pos3_sub.png,houses,dustbin,man,car,2_r.wav,The policeman will arrest the man,restrictive,3,3000
3,3,4_pos4_nosub.png,4_pos4_sub.png,plant,stool,rocking-horse,baby,3_r.wav,The woman will bathe the baby,restrictive,4,3000
4,4,5_pos1_nosub.png,5_pos1_sub.png,ball,paper-plane,acorns,shuttle-cock,4_r.wav,The boy will bounce the ball,restrictive,1,3000
5,5,6_pos2_nosub.png,6_pos2_sub.png,moon,mountain,animal,cactus,5_r.wav,The hiker will climb the mountain,restrictive,2,3000
6,6,7_pos3_nosub.png,7_pos3_sub.png,weighing-scales,jug,mushrooms,knife,6_r.wav,The housewife will fry the mushrooms,restrictive,3,3000
7,7,8_pos4_nosub.png,8_pos4_sub.png,tv-monitor,toy-bear,microscope,child,7_r.wav,The doctor will inject the child,restrictive,4,3000
8,8,9_pos1_nosub.png,9_pos1_sub.png,piano,table,telephone,television,8_r.wav,The woman will play the piano,restrictive,1,3000
9,9,10_pos2_nosub.png,10_pos2_sub.png,bag,book,door,cup,9_r.wav,The woman will read the book,restrictive,2,3000
10,10,11_pos3_nosub.png,11_pos3_sub.png,dog,wastebin,washing-machine,mirror,10_r.wav,The man will repair the washing machine,restrictive,3,3000
11,11,12_pos4_nosub.png,12_pos4_sub.png,drum,duck,bricks,bell,11_r.wav,The baby will ring the bell,restrictive,4,3000
12,12,13_pos1_nosub.png,13_pos1_sub.png,boat,birds,sun,car,12_r.wav,The man will sail the boat,restrictive,1,3000
13,13,14_pos2_nosub.png,14_pos2_sub.png,glasses,cigarettes,filofax,briefcase,13_r.wav,The man will smoke the cigarettes,restrictive,2,3000
14,14,15_pos3_nosub.png,15_pos3_sub.png,ball,hen,dog,bird,14_r.wav,The boy will walk the dog,restrictive,3,3000
15,15,16_pos4_nosub.png,16_pos4_sub.png,wallet,magnifying-glass,folder,hat,15_r.wav,The businessman will wear the hat,restrictive,4,3000
16,16,17_pos1_nosub.png,17_pos1_sub.png,dress,lantern,backpack,ribbon,16_r.wav,The woman will wear the dress,restrictive,1,3000
17,17,18_pos2_nosub.png,18_pos2_sub.png,rope,wood,bucket,stone,17_r.wav,The man will chop the wood,restrictive,2,3000
18,18,19_pos3_nosub.png,19_pos3_sub.png,feather,leaf,football,stick,18_r.wav,The boy will kick the football,restrictive,3,3000
19,19,20_pos4_nosub.png,20_pos4_sub.png,spoon,spatula,bowl,bread,19_r.wav,The chef will slice the bread,restrictive,4,3000
20,20,21_pos1_nosub.png,21_pos1_sub.png,kitten,block,crayon,cup,20_r.wav,The baby will hug the kitten,restrictive,1,3000
21,21,22_pos2_nosub.png,22_pos2_sub.png,cushion,flower,magazine,vase,21_r.wav,The woman will water the flower,restrictive,2,3000
22,22,23_pos3_nosub.png,23_pos3_sub.png,poster,towel,coat,hook,22_r.wav,The girl will zip the coat,restrictive,3,3000
23,23,24_pos4_nosub.png,24_pos4_sub.png,pencil,needle,card,scarf,23_r.wav,The girl will knit the scarf,restrictive,4,3000
24,24,25_pos1_nosub.png,25_pos1_sub.png,rabbit,plate,potato,glass,24_r.wav,The girl will groom the rabbit,restrictive,1,3000
25,25,26_pos2_nosub.png,26_pos2_sub.png,rope,canvas,keyboard,peach,25_n.wav,The man will move the canvas,non-restrictive,2,3000
26,26,27_pos3_nosub.png,27_pos3_sub.png,coin,coaster,candle,package,26_n.wav,The woman will blow grab the candle,non-restrictive,3,3000
27,27,28_pos4_nosub.png,28_pos4_sub.png,switch,frame,picture,lamp,27_n.wav,The boy will touch the lamp,non-restrictive,4,3000
28,28,29_pos1_nosub.png,29_pos1_sub.png,milk,glove,nut,sock,28_n.wav,The cat will push the milk,non-restrictive,1,3000
29,29,30_pos2_nosub.png,30_pos2_sub.png,tissue,newspaper,comb,eraser,29_n.wav,The grandmother will eadturn the newspaper,non-restrictive,2,3000
30,30,31_pos3_nosub.png,31_pos3_sub.png,watch,headphones,dice,cap,30_n.wav,The girl will grab the dice,non-restrictive,3,3000
31,31,32_pos4_nosub.png,32_pos4_sub.png,lemon,sponge,seed,bottle,31_n.wav,The woman will examine the bottle,non-restrictive,4,3000
32,32,33_pos1_nosub.png,33_pos1_sub.png,beer,mug,biscuit,kettle,32_n.wav,The woman will carry the beer,non-restrictive,1,3000
33,33,34_pos2_nosub.png,34_pos2_sub.png,gift,suitcase,envelope,box,33_n.wav,The boy will open the suitcase,non-restrictive,2,3000
34,34,35_pos3_nosub.png,35_pos3_sub.png,notebook,pillow,radio,puzzle,34_n.wav,The boy will move the radio,non-restrictive,3,3000
35,35,36_pos4_nosub.png,36_pos4_sub.png,brush,mirror,pot,mascara,35_n.wav,The girl will squeeze the mascara,non-restrictive,4,3000
36,36,37_pos1_nosub.png,37_pos1_sub.png,lego,papers,boxes,clips,36_n.wav,The kid will stack the lego,non-restrictive,1,3000
37,37,38_pos2_nosub.png,38_pos2_sub.png,key,banana,mitten,marker,37_n.wav,The boy will move the banana,non-restrictive,2,3000
38,38,39_pos3_nosub.png,39_pos3_sub.png,broom,cloth,apron,mop,38_n.wav,The woman will carry the apron,non-restrictive,3,3000
39,39,40_pos4_nosub.png,40_pos4_sub.png,shampoo,mat,buckle,shoelace,39_n.wav,The boy will move the shoelace,non-restrictive,4,3000
40,40,41_pos1_nosub.png,41_pos1_sub.png,blouse,pin,toothbrish,iron,40_n.wav,The girl will hold the blouse,non-restrictive,1,3000
41,41,42_pos2_nosub.png,42_pos2_sub.png,shell,orange,stone,cone,41_n.wav,The boy will move the orange,non-restrictive,2,3000
42,42,43_pos3_nosub.png,43_pos3_sub.png,chalk,ruler,shirt,apple,42_n.wav,The woman will wash the shirt,non-restrictive,3,3000
43,43,44_pos4_nosub.png,44_pos4_sub.png,pan,bolt,handle,safe,43_n.wav,The man will wipe the safe,non-restrictive,4,3000
44,44,45_pos1_nosub.png,45_pos1_sub.png,dough,glass,ladle,hammer,44_n.wav,The baker will inspect the dough,non-restrictive,1,3000
45,45,46_pos2_nosub.png,46_pos2_sub.png,pot,carrot,laddle,peeler,45_n.wav,The chef will carry the carrot,non-restrictive,2,3000
46,46,47_pos3_nosub.png,47_pos3_sub.png,gum,stand,violin,bow,46_n.wav,The musician will move the violin,non-restrictive,3,3000
47,47,48_pos4_nosub.png,48_pos4_sub.png,dustpan,roller,footstool,carpet,47_n.wav,The girl will move the carpet,non-restrictive,4,3000
48,48,49_pos1_nosub.png,49_pos1_sub.png,stamp,envelope,rubberband,scissors,48_n.wav,The child will inlatecarry the balloon,non-restrictive,1,3000
49,49,50_pos2_nosub.png,50_pos2_sub.png,pouch,balloon,pump,flag,49_n.wav,The man will pick up the stamp,non-restrictive,2,3000

In [ ]:
#filter invalid samples based on BPOGV (if BPOGV is false not bnoth eyes have been detected.)
#maybe we should introduce cutpoff for trials where only a low number of gaze samples are valid...?

samples_valid = gazeSamples_df_reduced[gazeSamples_df_reduced["BPOGV"] != 0]
samples_valid

,TIME,BPOGX,BPOGY,BPOGV,RPUPILV,LPUPILV,USER
0,685.56415,0.48626,0.42620,1,1,1,NaN
1,685.57068,0.47311,0.44338,1,1,1,START_TRIAL
2,685.57751,0.47556,0.42004,1,1,1,NaN
3,685.58447,0.47493,0.40582,1,1,1,NaN
4,685.59119,0.48930,0.41945,1,1,1,NaN
...,...,...,...,...,...,...,...
49639,1170.77979,0.21854,0.42355,1,1,1,NaN
49640,1170.78662,0.21402,0.42516,1,1,1,AUDIO_FILE_OFFSET
49641,1170.79333,0.21217,0.41835,1,1,1,NaN
49642,1170.79993,0.21452,0.42395,1,1,1,NaN
49643,1170.80627,0.21600,0.41312,1,1,1,NaN

In [ ]:
#the AOIs for the 4 objects have these positions in image coords (top left aligned just as open gaze as well):
#AOIS have size of 400x400
positions = {
    "pos1": (1782, 378),
    "pos2": (1342, 825),
    "pos3": (657, 825),
    "pos4": (217, 378),
}
#also it seems the screen resolution was at 1920x1080, if i read it coirrectly fromm the logfile. so we should change this for the real trials!
#for now we need to convert image coords to screen coords that we have in open gaze. 

#TODO

In [ ]:
#we also want to filter all samples and only keep those that are in the relevant time frame for each trial.
#this is inbeteween VERB ONSET ( called root start) and TARGET OBJECT ONSET (called dobj start)
#we can reference annotation_audiov1.csv for this.

#TODO